name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source ${{ github.workspace }}/venv/bin/activate
        pip install -r ${{ github.workspace }}/requirements_3.10.txt

    - name: Run tests
      env:
        PIXELBRAIN_PATH: ${{ github.workspace }}
        PYTHONPATH: ${{ github.workspace }}/src/:${{ github.workspace }}/src/tests
        CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        MONGODB_ATLAS_KEY: ${{ secrets.MONGODB_ATLAS_KEY }}
      run: |
        ./scripts/run_unit_tests.sh --time-tests --include-slow-suit